namespace :one_off do
  desc "One off task for generating an ndJSON file of all PaperTrail versions for BigQuery"
  task generate_versions_json_for_bigquery: :environment do
    # This task generates an ndJSON file that can be loaded into BigQuery via the cloud shell using:
    # bq load --noreplace --source_format=NEWLINE_DELIMITED_JSON npq_events_production.events ./bigquery_events_production.ndjson ./bigquery_events_schema.json
    # where bigquery_events_production.ndjson is the file generated by this task, and bigquery_events_schema.json is the schema file copied from the BigQuery console.
    Rails.logger = Logger.new($stdout) unless Rails.env.test?
    Rails.logger.level = Logger::INFO

    output_file_path = Rails.root.join("tmp/bigquery_events_#{Rails.env}.ndjson")

    query = PaperTrail::Version.where(id: [1_185_791, ..1_185_789]) # for some reason PaperTrail::Version ID:1185791 is missing in BigQuery
    Rails.logger.info "Generating JSON for #{query.count} PaperTrail versions"
    File.open(output_file_path, "w") do |file|
      query.find_each(batch_size: 1000) do |version|
        record = {
          occurred_at: version.created_at.utc.to_s,
          event_type: "version",
          DATA: version.send(:analytics_data).flat_map { |key, value| [{ key: key, value: Array.wrap(value) }] },
          environment: Rails.env,
          namespace: "npq",
        }
        file.puts(record.to_json)
      end
    end
    Rails.logger.info "Generated JSON file at #{output_file_path}"
  end
end
