name: Build and push Docker image
description: Builds a Docker image and pushes it to Dockerhub and GitHub container registry

inputs:
  dockerhub-username:
    description: CPD dockerhub account username
    required: true
  dockerhub-password:
    description: CPD dockerhub account password
    required: true
  account:
    description: DockerHub account, the part of the org/app:tag before the colon
    required: true
  tag:
    description: Tag for the Docker image
    required: true
  github-token:
    description: GitHub access token
    required: true

outputs:
  docker_image_id:
    description: The Docker image ID returned by the build step
    value: ${{ steps.docker_build_push.outputs.digest }}

runs:
  using: composite

  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      id: docker_build_push
      with:
        context: .
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          GIT_COMMIT_SHA=${{ github.sha }}
        push: true
        tags: |
          ${{ inputs.account }}:${{ inputs.tag }}
          ghcr.io/dfe-digital/npq-registration:${{ github.event.pull_request.head.sha || github.sha }}
        provenance: false
