inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'vendor/**/*'

Rails/ApplicationController:
  Exclude:
    - "app/controllers/monitoring_controller.rb"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/*"

Style/HashLikeCase:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Rails/SaveBang:
  Exclude:
    - "app/models/external/ecf_api/base.rb"
    - "app/services/ecf/ecf_user_creator.rb"
    - "app/services/ecf/npq_profile_creator.rb"
    - "app/services/ecf/npq_profile_updater.rb"

Rails/Output:
  Exclude:
    - "app/services/importers/*"
    - "app/services/exporters/*"

Naming/MethodParameterName:
  Enabled: false

RSpec/FilePath:
  Enabled: true

RSpec/AnyInstance:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - review
    - sandbox
    - staging
    - test
