inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'vendor/**/*'

Rails/ApplicationController:
  Exclude:
    - "app/controllers/monitoring_controller.rb"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/*"

Style/HashLikeCase:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Rails/SaveBang:
  Exclude:
    - "app/lib/ecf_api/base.rb"
    - "app/lib/services/ecf_user_creator.rb"
    - "app/lib/services/npq_profile_creator.rb"

Rails/Output:
  Exclude:
    - "app/lib/services/importers/*"
    - "app/lib/services/exporters/*"

Naming/MethodParameterName:
  Enabled: false
