inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'vendor/**/*'

Rails/ApplicationController:
  Exclude:
    - "app/controllers/monitoring_controller.rb"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/*"

Style/HashLikeCase:
  Enabled: false

Rails/Delegate:
  Enabled: false
