version: '3.6'

volumes:
  dbdata:

services:
  db:
    image: postgres:11-alpine
    restart: always
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=npq_registration_local

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=npq_registration_local
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=abcd1234
      - GOVUK_NOTIFY_API_KEY=addnotifykeyhere
