x-app: &app
  build:
    args:
      - BUNDLE_WITHOUT=production review separation
      - EXTRA_PACKAGES=chromium chromium-chromedriver gcompat yarn
    context: .
  depends_on:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres@db:5432/
    - ECF_DATABASE_URL=postgresql://postgres@db:5432/
    - RAILS_ENV=development
    - RAILS_LOG_TO_STDOUT=true
    - RAILS_SERVE_STATIC_FILES=true
    - SECRET_KEY_BASE=abcd1234
  volumes:
    - .:/app

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  ops:
    build:
      dockerfile_inline: |
        FROM mcr.microsoft.com/azure-cli:cbl-mariner2.0
        RUN mkdir /app
        WORKDIR /app
        RUN yum install -y git make tar unzip
        RUN az aks install-cli
        RUN curl -O https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip && \
          unzip terraform_1.5.4_linux_amd64.zip && \
          mv terraform /usr/local/bin/
    command: bash
    scale: 0
    volumes:
      - azure-data:/root/.azure
      - .:/app

  web:
    <<: *app
    command: bin/dev
    ports:
      - 3000:3000
    shm_size: '512mb' # required for chromium / selenium

  worker:
    <<: *app
    command: bundle exec rake jobs:work

volumes:
  azure-data:
  db-data:
