volumes:
  dbdata:

services:
  db:
    image: postgres:14-alpine
    restart: always
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_COMMIT_SHA: DOCKER_COMPOSE_GIT_COMMIT_SHA
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/npq_registration_local
      - ECF_DATABASE_URL=postgresql://root:password@db:5432/early_careers_framework_local
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=abcd1234
      - GOVUK_NOTIFY_API_KEY=addnotifykeyhere
