version: '3.6'

volumes:
  dbdata:

services:
  db:
    image: postgres:11-alpine
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=developmentpassword

  web:
    image: dfedigital/govuk-rails-boilerplate:${BRANCH_TAG:-latest}
    command: ash -c "bundle exec rails db:setup db:migrate && bundle exec rails server -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - RAILS_ENV=production
      - DB_HOST=db
      - DB_DATABASE=rails-boilerplate
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - SECRET_KEY_BASE=abcd1234
      - RAILS_SERVE_STATIC_FILES=true
