services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  ops:
    build:
      dockerfile_inline: |
        FROM mcr.microsoft.com/azure-cli:cbl-mariner2.0
        RUN mkdir /app
        WORKDIR /app
        RUN yum install -y make
        RUN az aks install-cli
    command: bash
    scale: 0
    volumes:
      - azure-data:/root/.azure
      - .:/app

  web:
    build:
      args:
        - BUNDLE_WITHOUT=production review separation
        - EXTRA_PACKAGES=chromium chromium-chromedriver gcompat yarn
      context: .
    command: bin/dev
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres@db:5432/
      - ECF_DATABASE_URL=postgresql://postgres@db:5432/
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=abcd1234
    ports:
      - 3000:3000
    shm_size: '512mb' # required for chromium / selenium
    volumes:
      - .:/app

volumes:
  azure-data:
  db-data:
