name: Deploy environment to AKS
description: Deploys an application environment to AKS

inputs:
  environment:
    description: The name of the environment
    required: true
  docker-image:
    description: The Docker image to deploy
    required: true
  azure-client-id:
    description: Azure Client ID for authentication
    required: true
  azure-tenant-id:
    description: Azure Tenant ID for authentication
    required: true
  azure-subscription-id:
    description: Azure Subscription ID for authentication
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy. If set, this will automatically seed the database.
    required: false
  deploy-commit-sha:
    description: The commit sha for the commit being deployed
    required: true
  statuscake-api-token:
    description: The Statuscake token
    required: false

outputs:
  url:
    description: The base URL for the deployed environment
    value: ${{ steps.apply-terraform.outputs.url }}

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.8
        terraform_wrapper: false

    - uses: Azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Apply Terraform
      id: apply-terraform
      shell: bash
      run: |
        make ci ${{ inputs.environment }} terraform-apply
        cd terraform/application && echo "url=$(terraform output -raw url)" >> $GITHUB_OUTPUT
      env:
        TF_VAR_statuscake_api_token: ${{ inputs.statuscake-api-token }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - name: Seed database
      if: inputs.pull-request-number != '' && inputs.environment != 'production'
      shell: bash
      run: |
        make ci review get-cluster-credentials
        kubectl exec -n cpd-development deployment/teacher-training-entitlement-review-${{ inputs.pull-request-number }}-web -- sh -c "cd /app && RAILS_ENV=${{ inputs.environment }} /usr/local/bin/bundle exec rails db:seed:replant"
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    # - uses: ./.github/actions/smoke-test
    #   with:
    #     url: ${{ steps.apply-terraform.outputs.url }}
    #     deploy-commit-sha: ${{ inputs.deploy-commit-sha }}
