// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GetAnIdentityRedirectButtonController from "./get_an_identity_redirect_button_controller"
application.register("get-an-identity-redirect-button", GetAnIdentityRedirectButtonController)
