module Courses
  DEFINITIONS = [
    {
      position: 0,
      name: "Early years leadership (NPQEYL)",
      ecf_id: "66dff4af-a518-498f-9042-36a41f9e8aa7",
      identifier: "npq-early-years-leadership",
      course_group_name: "leadership",
      display: true,
      short_code: "NPQEYL",
    },
    {
      position: 1,
      name: "Executive leadership (NPQEL)",
      ecf_id: "aef853f2-9b48-4b6a-9d2a-91b295f5ca9a",
      identifier: "npq-executive-leadership",
      course_group_name: "leadership",
      display: true,
      short_code: "NPQEL",
    },
    {
      position: 2,
      name: "Headship (NPQH)",
      ecf_id: "0f7d6578-a12c-4498-92a0-2ee0f18e0768",
      identifier: "npq-headship",
      course_group_name: "leadership",
      display: true,
      short_code: "NPQH",
    },
    {
      position: 3,
      name: "Leading behaviour and culture (NPQLBC)",
      ecf_id: "7d47a0a6-fa74-4587-92cc-cd1e4548a2e5",
      identifier: "npq-leading-behaviour-culture",
      course_group_name: "specialist",
      display: true,
      short_code: "NPQLBC",
    },
    {
      position: 4,
      name: "Leading literacy (NPQLL)",
      ecf_id: "829fcd45-e39d-49a9-b309-26d26debfa90",
      identifier: "npq-leading-literacy",
      course_group_name: "specialist",
      display: true,
      short_code: "NPQLL",
    },
    {
      position: 5,
      name: "Leading primary mathematics (NPQLPM)",
      ecf_id: "7866f853-064f-44b4-9287-20b9993452d6",
      identifier: "npq-leading-primary-mathematics",
      course_group_name: "specialist",
      display: true,
      short_code: "NPQLPM",
    },
    {
      position: 6,
      name: "Leading teaching (NPQLT)",
      ecf_id: "15c52ed8-06b5-426e-81a2-c2664978a0dc",
      identifier: "npq-leading-teaching",
      course_group_name: "specialist",
      description: "Lead teaching and learning for a subject, year group or phase",
      display: true,
      short_code: "NPQLT",
    },
    {
      position: 7,
      name: "Leading teacher development (NPQLTD)",
      ecf_id: "29fee78b-30ce-4b93-ba21-80be2fde286f",
      identifier: "npq-leading-teaching-development",
      course_group_name: "specialist",
      description: "Develop other teachers and support their professional growth",
      display: true,
      short_code: "NPQLTD",
    },
    {
      position: 8,
      name: "Senior leadership (NPQSL)",
      ecf_id: "a42736ad-3d0b-401d-aebe-354ef4c193ec",
      identifier: "npq-senior-leadership",
      course_group_name: "leadership",
      display: true,
      short_code: "NPQSL",
    },
    {
      position: 9,
      name: "Special educational needs co-ordinator (NPQSENCO)",
      ecf_id: "d8662dbd-f50a-4bbf-a9dd-359e1d32e050",
      identifier: "npq-senco",
      course_group_name: "leadership",
      display: true,
      short_code: "NPQSENCO",
    },
    {
      position: 10,
      name: "Early headship coaching offer (EHCO)",
      ecf_id: "0222d1a8-a8e1-42e3-a040-2c585f6c194a",
      identifier: "npq-early-headship-coaching-offer",
      course_group_name: "ehco",
      description: "Networking and support if you’re in your first 5 years of headship",
      display: true,
      short_code: "EHCO",
    },
    {
      position: 11,
      name: "Additional support offer for new headteachers (ASO)",
      ecf_id: "7fbefdd4-dd2d-4a4f-8995-d59e525124b7",
      identifier: "npq-additional-support-offer",
      course_group_name: "support",
      description: "The Additional Support Offer is a targeted support package for new headteachers.",
      display: false,
      short_code: "ASO",
    },
  ].freeze
end
