# frozen_string_literal: true

# need to disable Lint/PercentStringArray here, because CSP keywords need to be single-quoted
# rubocop:disable Lint/PercentStringArray
SecureHeaders::Configuration.default do |config|
  config.x_frame_options = "DENY"
  config.x_content_type_options = "nosniff"
  config.x_xss_protection = "0"
  config.x_download_options = "noopen"
  config.x_permitted_cross_domain_policies = "none"
  config.referrer_policy = %w[origin-when-cross-origin strict-origin-when-cross-origin]

  google_analytics = %w[*.google-analytics.com *.analytics.google.com *.googletagmanager.com tagmanager.google.com *.googleusercontent.com *.gstatic.com]
  tracking_pixels = %w[www.facebook.com px.ads.linkedin.com]
  flippercloud = %w[www.flippercloud.io]
  identity_domain = [ENV["TRA_OIDC_DOMAIN"]]
  sentry = %w[*.sentry-cdn.com *.ingest.us.sentry.io]

  if ENV["SENTRY_CSP_REPORT_URI"]
    sentry_report_uri = ENV["SENTRY_CSP_REPORT_URI"]
    sentry += [URI(sentry_report_uri).host]
  end

  # Inline CSS tags generated by mermaid.js on /api/guidance
  mermaid_hashes = %w[
    'sha256-BA/Gli0hPSrz76uVU0pnVOODwCmNs/0MS1t1lFGjepc='
    'sha256-XT2L7Jw8e6M4QkDyl+Xyzztltvm63ImlBm8uIhEHEhs='
    'sha256-yTxo/q79syvY2yrJeaOeHOMlCCVl9Dc9eFN8n3xtsnE='
    'sha256-qxhWPxIUhnkkqKKOEkgc+sHkWzZLsNYZ1t5u8nXu8Ow='
    'sha256-ypVm1MFyuMqjbBGFUoGuO6z/TSOou4pOKCWGwDsBpVE='
    'sha256-TzehWAMojJ5MxaZO6tsQSnEi6nKOaRykGEiAp4tjJmQ='
    'sha256-bdFQN2V44FhEiuEdcuhiO/f9a9GffZ6wMA7cDqjsmyU='
    'sha256-yF31XkcjW8+bDmx2alVbC+p6QqP+u+r1aHBGK8F+NgE='
    'sha256-dSqngQm56l3bKjTKuu+9/kJLc5WyGvbPdXL0IXNpE3U='
    'sha256-aOKu38ec/bSbd1BWfOZWow6kP78MsLOsTmNyCpYqsXM='
    'sha256-/C1QaJLa62GGZNKqOC3O9KFjhee13cDjlEz1UmUHArM='
    'sha256-hOZb66TfkgAaNnY2OdFxDYyWA3V908VnWh25XbuyobY='
    'sha256-GT96nSmpiJCC10Sq1KUK0oz/tv/0F/5CaXsc1hN24lY='
    'sha256-bZ84B82ibs+wuOxEH0aGXyYAelrEGe1hfYRSKYq3++M='
    'sha256-NZLQvdTTZtrktFDkzPeufcUBlW9EwQVrDp/YV7nMphM='
    'sha256-arI7Emm7hrW+TNARAWQq+Br8Oees52L81i4YWXLJJ54='
    'sha256-SI5Gio2oe14yTxmeUlTEg6kZ40eDY7klt8iQ1KTjrc4='
    'sha256-4lxsnlWYidLkz2pfmH3qGXJ6atp0dmQNWq1W9FY+zsE='
    'sha256-mz45UwNfu4/B3seQ9UT8ifJFjBmpxwn4bNGxI3Lvono='
    'sha256-8LvyI2zPhVpiJoxIQ2eZrbDy6v4Mf+NPs+aX8IJt95o='
    'sha256-6m+Pxpjk+jyp7HZXpcce2aAhz5qolnf72N5ndxd4BSQ='
  ]

  # These are for the inline CSS in the flipper admin UI
  flipper_ui_hashes = %w[
    'sha256-NNzAJMHPK9KuPslppuoTz2azqZcpUO0IJZosehbmhHA='
    'sha256-zuOhDbTpAZjaeemuptCNLaf/7IaV06c8De4EMGOhtzM='
  ]

  # This is for the inline style browsers apply to robots.txt file
  robots_txt_inline_style_hash = %w[
    'sha256-4Su6mBWzEIFnH4pAGMOuaeBrstwJN4Z3pq/s1Kn4/KQ='
  ]

  all_hashes = flipper_ui_hashes + robots_txt_inline_style_hash + mermaid_hashes

  config.csp = SecureHeaders::OPT_OUT

  config.csp_report_only = {
    upgrade_insecure_requests: true,
    disable_nonce_backwards_compatibility: true,
    default_src: %w['none'],
    base_uri: %w['self'],
    child_src: %w['self'],
    connect_src: %w['self'] + google_analytics + flippercloud + sentry,
    font_src: %w['self' *.gov.uk fonts.gstatic.com],
    form_action: %w['self'] + identity_domain, # needed because the POST to /users/auth/tra_openid_connect' redirects to the identity domain
    frame_ancestors: %w['self'],
    frame_src: %w['self'] + google_analytics,
    img_src: %w['self' data: *.gov.uk] + google_analytics + tracking_pixels,
    manifest_src: %w['self'],
    media_src: %w['self'],
    script_src: %w['self' *.gov.uk https://cdn.jsdelivr.net/npm/chart.js] + google_analytics + sentry,
    style_src: %w['self' *.gov.uk fonts.googleapis.com] + google_analytics + %w['unsafe-hashes'] + all_hashes,
    worker_src: %w['self'],
    report_uri: [sentry_report_uri],
  }
end
# rubocop:enable Lint/PercentStringArray
