---
shared:
  :statement_items:
    - id
    - statement_id
    - state
    - created_at
    - updated_at
    - declaration_id
    - ecf_id
  :statements:
    - id
    - month
    - year
    - deadline_date
    - payment_date
    - output_fee
    - cohort_id
    - lead_provider_id
    - marked_as_paid_at
    - state
    - created_at
    - updated_at
    - ecf_id
  :schools:
    - id
    - urn
    - establishment_number
    - name
    - close_date
    - ukprn
    - last_changed_date
    - address_1
    - address_2
    - address_3
    - town
    - county
    - postcode
    - easting
    - northing
    - region
    - country
    - created_at
    - updated_at
    - high_pupil_premium
    - postcode_without_spaces
    - eyl_funding_eligible
  :schedules:
    - id
    - course_group_id
    - cohort_id
    - name
    - identifier
    - applies_from
    - applies_to
    - allowed_declaration_types
    - created_at
    - updated_at
    - ecf_id
  :registration_interests:
    - id
    - email
    - notified
    - created_at
    - updated_at
  :private_childcare_providers:
    - id
    - provider_urn
    - provider_name
    - registered_person_urn
    - registered_person_name
    - registration_date
    - provider_status
    - address_1
    - address_2
    - address_3
    - town
    - postcode
    - postcode_without_spaces
    - region
    - local_authority
    - ofsted_region
    - early_years_individual_registers
    - provider_early_years_register_flag
    - provider_compulsory_childcare_register_flag
    - places
    - created_at
    - updated_at
    - disabled_at
  :participant_outcome_api_requests:
    - id
    - ecf_id
    - participant_outcome_id
    - request_path
    - status_code
    - request_headers
    - request_body
    - response_body
    - response_headers
    - created_at
    - updated_at
  :participant_outcomes:
    - id
    - state
    - completion_date
    - declaration_id
    - qualified_teachers_api_request_successful
    - sent_to_qualified_teachers_api_at
    - created_at
    - updated_at
    - ecf_id
  :participant_id_changes:
    - id
    - user_id
    - created_at
    - updated_at
    - ecf_id
    - from_participant_id
    - to_participant_id
  :local_authorities:
    - id
    - ukprn
    - name
    - address_1
    - address_2
    - address_3
    - town
    - county
    - postcode
    - postcode_without_spaces
    - high_pupil_premium
    - created_at
    - updated_at
  :lead_providers:
    - id
    - name
    - created_at
    - updated_at
    - ecf_id
    - hint
  :itt_providers:
    - id
    - legal_name
    - operating_name
    - removed_at
    - approved
    - created_at
    - updated_at
    - disabled_at
  :delivery_partners:
    - id
    - ecf_id
    - name
    - created_at
    - updated_at
  :delivery_partnerships:
    - id
    - delivery_partner_id
    - lead_provider_id
    - cohort_id
    - created_at
    - updated_at
  :declarations:
    - id
    - ecf_id
    - application_id
    - superseded_by_id
    - lead_provider_id
    - cohort_id
    - declaration_type
    - declaration_date
    - state
    - state_reason
    - created_at
    - updated_at
    - delivery_partner_id
    - secondary_delivery_partner_id
  :course_groups:
    - id
    - name
    - created_at
    - updated_at
  :courses:
    - id
    - name
    - created_at
    - updated_at
    - ecf_id
    - description
    - display
    - identifier
    - course_group_id
  :cohorts:
    - id
    - start_year
    - registration_start_date
    - created_at
    - updated_at
    - funding_cap
    - ecf_id
    - name
    - description
  :application_states:
    - id
    - application_id
    - lead_provider_id
    - state
    - reason
    - created_at
    - updated_at
    - ecf_id
  :applications:
    - id
    - user_id
    - course_id
    - lead_provider_id
    - created_at
    - updated_at
    - ecf_id
    - headteacher_status
    - eligible_for_funding
    - funding_choice
    - ukprn
    - teacher_catchment
    - teacher_catchment_country
    - works_in_school
    - employer_name
    - employment_role
    - works_in_nursery
    - works_in_childcare
    - kind_of_nursery
    - targeted_delivery_funding_eligibility
    - funding_eligiblity_status_code
    - work_setting
    - teacher_catchment_synced_to_ecf
    - employment_type
    - lead_mentor
    - primary_establishment
    - number_of_pupils
    - tsf_primary_eligibility
    - tsf_primary_plus_eligibility
    - lead_provider_approval_status
    - participant_outcome_state
    - private_childcare_provider_id
    - itt_provider_id
    - school_id
    - teacher_catchment_iso_country_code
    - targeted_support_funding_eligibility
    - notes
    - cohort_id
    - funded_place
    - training_status
    - schedule_id
    - referred_by_return_to_teaching_adviser
    - accepted_at
    - senco_in_role
    - senco_start_date
    - on_submission_trn
    - review_status
  :users:
    - id
    - created_at
    - updated_at
    - ecf_id
    - trn_verified
    - trn
    - active_alert
    - trn_auto_verified
    - feature_flag_id
    - provider
    - uid
    - get_an_identity_id_synced_to_ecf
    - updated_from_tra_at
    - trn_lookup_status
    - notify_user_for_future_reg
    - email_updates_status
    - email_updates_unsubscribe_key
    - archived_at
    - significantly_updated_at
