---
shared:
  :registration_interests:
    - email
  :private_childcare_providers:
    - registered_person_name
  :contracts:
    - id
    - statement_id
    - course_id
    - contract_template_id
    - created_at
    - updated_at
