
shared_db_settings: &shared_db_settings
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

default_primary: &default_primary
  <<: *shared_db_settings
  database: "<%= ENV['DB_DATABASE'] %>"
  username: "<%= ENV['DB_USERNAME'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"
  host: "<%= ENV['DB_HOST'] %>"
  port: "<%= ENV['DB_PORT'] %>"
  url: <%= ENV.fetch("DATABASE_URL", "postgres://localhost:5432") %>

development:
  <<: *default_primary
  database: npq_registration_development

review:
  <<: *default_primary

test:
  <<: *default_primary
  database: npq_registration_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default_primary

sandbox:
  <<: *default_primary

production:
  <<: *default_primary
