get:
  "/api/v1/npq-applications":
    paginate: true
  "/api/v2/npq-applications":
    paginate: true
  "/api/v3/npq-applications":
    paginate: true

  "/api/v1/npq-applications?filter[cohort]=2023":
    paginate: true
  "/api/v2/npq-applications?filter[cohort]=2023":
    paginate: true
  "/api/v3/npq-applications?filter[cohort]=2023":
    paginate: true

  "/api/v1/npq-applications?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/npq-applications?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/npq-applications?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true

  "/api/v1/npq-applications?filter[cohort]=2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/npq-applications?filter[cohort]=2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/npq-applications?filter[cohort]=2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true

  "/api/v3/npq-applications?filter[participant_id]=:id":
    paginate: true
    id: application_ecf_id
  "/api/v3/npq-applications?filter[participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: application_ecf_id
  "/api/v3/npq-applications?filter[participant_id]=:id&filter[cohort]=2023":
    paginate: true
    id: application_ecf_id
  "/api/v3/npq-applications?filter[participant_id]=:id&filter[cohort]=2023&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: application_ecf_id

  "/api/v1/npq-applications/:id":
    id: application_ecf_id
  "/api/v2/npq-applications/:id":
    id: application_ecf_id
  "/api/v3/npq-applications/:id":
    id: application_ecf_id

  "/api/v1/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participant-declarations?filter[type]=npq&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations?filter[type]=npq&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations?filter[type]=npq&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participant-declarations?filter[type]=npq&filter[participant_id]=:id":
    paginate: true
    id: participant_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations?filter[type]=npq&filter[participant_id]=:id":
    paginate: true
    id: participant_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations?filter[type]=npq&filter[participant_id]=:id":
    paginate: true
    id: participant_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participant-declarations?filter[type]=npq&filter[participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: participant_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations?filter[type]=npq&filter[participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: participant_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations?filter[type]=npq&filter[participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: participant_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participants/npq/outcomes":
    paginate: true
  "/api/v2/participants/npq/outcomes":
    paginate: true
  "/api/v3/participants/npq/outcomes":
    paginate: true

  "/api/v1/participants/npq/outcomes?filter[created_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/participants/npq/outcomes?filter[created_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq/outcomes?filter[created_since]=2023-11-13T11:21:55Z":
    paginate: true

  "/api/v1/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id
  "/api/v2/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id
  "/api/v3/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id

  "/api/v1/participants/npq":
    paginate: true
  "/api/v2/participants/npq":
    paginate: true
  "/api/v3/participants/npq":
    paginate: true

  "/api/v1/participants/npq?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/participants/npq?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq?filter[training_status]=active":
    paginate: true
  "/api/v3/participants/npq?filter[training_status]=active&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq?filter[from_participant_id]=:id":
    paginate: true
    id: participant_ecf_id
  "/api/v3/participants/npq?filter[from_participant_id]=:id&filter[training_status]=active":
    paginate: true
    id: participant_ecf_id
  "/api/v3/participants/npq?filter[from_participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: participant_ecf_id
  "/api/v3/participants/npq?filter[from_participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z&filter[training_status]=active":
    paginate: true
    id: participant_ecf_id

  "/api/v1/participants/npq/:id":
    id: participant_ecf_id
  "/api/v2/participants/npq/:id":
    id: participant_ecf_id
  "/api/v3/participants/npq/:id":
    id: participant_ecf_id

  "/api/v3/statements?filter[type]=npq":
    paginate: true
    exclude:
      - type
  "/api/v3/statements?filter[type]=npq&filter[cohort]=2022,2023":
    paginate: true
    exclude:
      - type
  "/api/v3/statements?filter[type]=npq&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
    exclude:
      - type
  "/api/v3/statements?filter[type]=npq&filter[cohort]=2022,2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
    exclude:
      - type

  "/api/v3/statements/:id":
    id: statement_ecf_id
    exclude:
      - type

post:
  "/api/v1/npq-applications/:id/accept#with_funded_place":
    exclude:
      - updated_at
    id: application_ecf_id_for_accept_with_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: true
  "/api/v2/npq-applications/:id/accept#with_funded_place":
    exclude:
      - updated_at
    id: application_ecf_id_for_accept_with_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: true
  "/api/v3/npq-applications/:id/accept#with_funded_place":
    exclude:
      - updated_at
    id: application_ecf_id_for_accept_with_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: true

  "/api/v1/npq-applications/:id/accept#without_funded_place":
    exclude:
      - updated_at
    id: application_ecf_id_for_accept_without_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: false
  "/api/v2/npq-applications/:id/accept#without_funded_place":
    exclude:
      - updated_at
    id: application_ecf_id_for_accept_without_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: false
  "/api/v3/npq-applications/:id/accept#without_funded_place":
    exclude:
      - updated_at
    id: application_ecf_id_for_accept_without_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: false

  "/api/v1/npq-applications/:id/reject":
    exclude:
      - updated_at
    id: application_ecf_id_for_reject
  "/api/v2/npq-applications/:id/reject":
    exclude:
      - updated_at
    id: application_ecf_id_for_reject
  "/api/v3/npq-applications/:id/reject":
    exclude:
      - updated_at
    id: application_ecf_id_for_reject

  "/api/v1/participant-declarations":
    exclude:
      - id
      - updated_at
      - created_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    payload: post_declaration_payload
  "/api/v2/participant-declarations":
    exclude:
      - id
      - updated_at
      - created_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    payload: post_declaration_payload
  "/api/v3/participant-declarations":
    exclude:
      - id
      - updated_at
      - created_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    payload: post_declaration_payload

  "/api/v1/participants/npq/:id/outcomes":
    exclude:
      - id
      - created_at
      - updated_at
    id: participant_ecf_id_for_create_outcome
    payload: post_participant_outcome_payload
  "/api/v2/participants/npq/:id/outcomes":
    exclude:
      - id
      - created_at
      - updated_at
    id: participant_ecf_id_for_create_outcome
    payload: post_participant_outcome_payload
  "/api/v3/participants/npq/:id/outcomes":
    exclude:
      - id
      - created_at
      - updated_at
    id: participant_ecf_id_for_create_outcome
    payload: post_participant_outcome_payload

put:
  "/api/v1/npq-applications/:id/change-funded-place":
    exclude:
      - updated_at
    id: application_ecf_id_for_change_from_funded_place
    payload:
      type: "npq-application-change-funded-place"
      attributes:
        funded_place: false
  "/api/v2/npq-applications/:id/change-funded-place":
    exclude:
      - updated_at
    id: application_ecf_id_for_change_from_funded_place
    payload:
      type: "npq-application-change-funded-place"
      attributes:
        funded_place: false
  "/api/v3/npq-applications/:id/change-funded-place":
    exclude:
      - updated_at
    id: application_ecf_id_for_change_from_funded_place
    payload:
      type: "npq-application-change-funded-place"
      attributes:
        funded_place: false

  "/api/v1/participant-declarations/:id/void#void":
    exclude:
      - updated_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    id: declaration_ecf_id_for_void
  "/api/v2/participant-declarations/:id/void#void":
    exclude:
      - updated_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    id: declaration_ecf_id_for_void
  "/api/v3/participant-declarations/:id/void#void":
    exclude:
      - updated_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    id: declaration_ecf_id_for_void

  "/api/v1/participant-declarations/:id/void#clawback":
    exclude:
      - updated_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    id: declaration_ecf_id_for_clawback
  "/api/v2/participant-declarations/:id/void#clawback":
    exclude:
      - updated_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    id: declaration_ecf_id_for_clawback
  "/api/v3/participant-declarations/:id/void#clawback":
    exclude:
      - updated_at
      - mentor_id
      - evidence_held
      - delivery_partner_id
    id: declaration_ecf_id_for_clawback

  "/api/v1/participants/npq/:id/resume":
    exclude:
      - updated_at
    id: participant_ecf_id_for_resume
    payload: put_participant_resume_payload
  "/api/v2/participants/npq/:id/resume":
    exclude:
      - updated_at
    id: participant_ecf_id_for_resume
    payload: put_participant_resume_payload
  "/api/v3/participants/npq/:id/resume":
    exclude:
      - updated_at
    id: participant_ecf_id_for_resume
    payload: put_participant_resume_payload

  "/api/v1/participants/npq/:id/defer":
    exclude:
      - updated_at
    id: participant_ecf_id_for_defer
    payload: put_participant_defer_payload
  "/api/v2/participants/npq/:id/defer":
    exclude:
      - updated_at
      - date
    id: participant_ecf_id_for_defer
    payload: put_participant_defer_payload
  "/api/v3/participants/npq/:id/defer":
    exclude:
      - updated_at
    id: participant_ecf_id_for_defer
    payload: put_participant_defer_payload

  "/api/v1/participants/npq/:id/withdraw":
    exclude:
      - updated_at
    id: participant_ecf_id_for_withdraw
    payload: put_participant_withdraw_payload
  "/api/v2/participants/npq/:id/withdraw":
    exclude:
      - updated_at
    id: participant_ecf_id_for_withdraw
    payload: put_participant_withdraw_payload
  "/api/v3/participants/npq/:id/withdraw":
    exclude:
      - updated_at
    id: participant_ecf_id_for_withdraw
    payload: put_participant_withdraw_payload
