get:
  "/api/v1/npq-applications":
    paginate: true
  "/api/v2/npq-applications":
    paginate: true
  "/api/v3/npq-applications":
    paginate: true

  "/api/v1/npq-applications/:id":
    id: application_ecf_id
  "/api/v2/npq-applications/:id":
    id: application_ecf_id
  "/api/v3/npq-applications/:id":
    id: application_ecf_id

  "/api/v1/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participants/npq/outcomes":
    paginate: true
  "/api/v2/participants/npq/outcomes":
    paginate: true 
  "/api/v3/participants/npq/outcomes":
    paginate: true

  "/api/v1/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id
  "/api/v2/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id
  "/api/v3/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id

  "/api/v1/participants/npq":
    paginate: true
  "/api/v2/participants/npq":
    paginate: true
  "/api/v3/participants/npq":
    paginate: true

  "/api/v1/participants/npq/:id":
    id: participant_ecf_id
  "/api/v2/participants/npq/:id":
    id: participant_ecf_id
  "/api/v3/participants/npq/:id":
    id: participant_ecf_id

  "/api/v3/statements?filter[type]=npq":
    paginate: true
    exclude:
      - type

  "/api/v3/statements/:id":
    id: statement_ecf_id
    exclude:
      - type
