get:
  "/api/v1/npq-applications?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/npq-applications?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/npq-applications?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true

  "/api/v1/npq-applications?filter[cohort]=2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/npq-applications?filter[cohort]=2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/npq-applications?filter[cohort]=2023&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true

  "/api/v3/npq-applications?filter[participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: application_ecf_id
  "/api/v3/npq-applications?filter[participant_id]=:id&filter[cohort]=2023&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: application_ecf_id

  "/api/v1/participants/npq?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v2/participants/npq?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq?filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq?filter[training_status]=active":
    paginate: true
  "/api/v3/participants/npq?filter[training_status]=active&filter[updated_since]=2023-11-13T11:21:55Z":
    paginate: true
  "/api/v3/participants/npq?filter[from_participant_id]=:id&filter[training_status]=active":
    paginate: true
    id: participant_ecf_id
  "/api/v3/participants/npq?filter[from_participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z":
    paginate: true
    id: participant_ecf_id
  "/api/v3/participants/npq?filter[from_participant_id]=:id&filter[updated_since]=2020-11-13T11:21:55Z&filter[training_status]=active":
    paginate: true
    id: participant_ecf_id
