get:
  "/api/v1/npq-applications":
    paginate: true
  "/api/v2/npq-applications":
    paginate: true
  "/api/v3/npq-applications":
    paginate: true

  "/api/v1/npq-applications/:id":
    id: application_ecf_id
  "/api/v2/npq-applications/:id":
    id: application_ecf_id
  "/api/v3/npq-applications/:id":
    id: application_ecf_id

  "/api/v1/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations?filter[type]=npq":
    paginate: true
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v2/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held
  "/api/v3/participant-declarations/:id":
    id: declaration_ecf_id
    exclude:
      - delivery_partner_id
      - mentor_id
      - evidence_held

  "/api/v1/participants/npq/outcomes":
    paginate: true
  "/api/v2/participants/npq/outcomes":
    paginate: true 
  "/api/v3/participants/npq/outcomes":
    paginate: true

  "/api/v1/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id
  "/api/v2/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id
  "/api/v3/participants/npq/:id/outcomes":
    id: participant_outcome_ecf_id

  "/api/v1/participants/npq":
    paginate: true
  "/api/v2/participants/npq":
    paginate: true
  "/api/v3/participants/npq":
    paginate: true

  "/api/v1/participants/npq/:id":
    id: participant_ecf_id
  "/api/v2/participants/npq/:id":
    id: participant_ecf_id
  "/api/v3/participants/npq/:id":
    id: participant_ecf_id

  "/api/v3/statements?filter[type]=npq":
    paginate: true
    exclude:
      - type

  "/api/v3/statements/:id":
    id: statement_ecf_id
    exclude:
      - type

post:
  "/api/v1/npq-applications/:id/accept#with_funded_place":
    id: application_ecf_id_for_accept_with_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: true
  "/api/v2/npq-applications/:id/accept#with_funded_place":
    id: application_ecf_id_for_accept_with_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: true
  "/api/v3/npq-applications/:id/accept#with_funded_place":
    id: application_ecf_id_for_accept_with_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: true

  "/api/v1/npq-applications/:id/accept#without_funded_place":
    id: application_ecf_id_for_accept_without_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: false
  "/api/v2/npq-applications/:id/accept#without_funded_place":
    id: application_ecf_id_for_accept_without_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: false
  "/api/v3/npq-applications/:id/accept#without_funded_place":
    id: application_ecf_id_for_accept_without_funded_place
    payload:
      type: "npq-application-accept"
      attributes:
        funded_place: false

  "/api/v1/npq-applications/:id/reject":
    id: application_ecf_id_for_reject
  "/api/v2/npq-applications/:id/reject":
    id: application_ecf_id_for_reject
  "/api/v3/npq-applications/:id/reject":
    id: application_ecf_id_for_reject

  "/api/v1/participant-declarations":
    payload: post_declaration_payload
  "/api/v2/participant-declarations":
    payload: post_declaration_payload
  "/api/v3/participant-declarations":
    payload: post_declaration_payload

  "/api/v1/participants/npq/:id/outcomes":
    id: participant_ecf_id_for_create_outcome
    payload: post_participant_outcome_payload
  "/api/v2/participants/npq/:id/outcomes":
    id: participant_ecf_id_for_create_outcome
    payload: post_participant_outcome_payload
  "/api/v3/participants/npq/:id/outcomes":
    id: participant_ecf_id_for_create_outcome
    payload: post_participant_outcome_payload
