---
# The authentication token for the application.
authentication: 0CmSyJVfcKitt5KSuaJJnAbjGVAze2xvWtYbdKb1CQU
log_file: tmp/skylight.log
ignored_endpoints:
  - MonitoringController#healthcheck
  - MonitoringController#up
