---
authentication: 0CmSyJVfcKitt5KSuaJJnAbjGVAze2xvWtYbdKb1CQU
deploy:
  git_sha: <%= ENV["COMMIT_SHA"] %>
ignored_endpoints:
  - MonitoringController#healthcheck
  - MonitoringController#up
log_file: tmp/skylight.log
