---
applications:
- name: npq-registration-dev
  processes:
  - type: web
    disk_quota: 2G
    memory: 512M
    health-check-http-endpoint: /healthcheck.json
    health-check-type: http
    health-check-invocation-timeout: 10
    instances: 1
  - type: worker
    disk_quota: 2G
    health-check-type: process
    instances: 1
    command: bundle exec rake jobs:work
  services:
    - npq-registration-dev-db
  env:
    DOCKER_IMAGE_ID: ((DOCKER_IMAGE_ID))
    ECF_APP_BASE_URL: "https://st.manage-training-for-early-career-teachers.education.gov.uk/"
    ECF_APP_BEARER_TOKEN: ((ECF_APP_BEARER_TOKEN))
    ENV: $HOME/.profile
    GET_AN_IDENTITY_WEBHOOK_SECRET: ((GET_AN_IDENTITY_WEBHOOK_SECRET))
    GOOGLE_ANALYTICS_ID: "G-4QYNT5ZME8"
    GOOGLE_BQ_SERVICE_ACCOUNT_BASE64: ((GOOGLE_BQ_SERVICE_ACCOUNT_BASE64))
    GOOGLE_TAG_MANAGER_ID: "GTM-N58Z5PG"
    GOVUK_NOTIFY_API_KEY: ((GOVUK_NOTIFY_API_KEY))
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    SECRET_KEY_BASE: ((SECRET_KEY_BASE))
    SENTRY_CURRENT_ENV: development
    SENTRY_DSN: ((SENTRY_DSN))
    SERVICE_ENV: development
    TRA_OIDC_CLIENT_ID: ((TRA_OIDC_CLIENT_ID))
    TRA_OIDC_CLIENT_SECRET: ((TRA_OIDC_CLIENT_SECRET))
    TRA_OIDC_DOMAIN: ((TRA_OIDC_DOMAIN))
    TRA_OIDC_REDIRECT_URI: ((TRA_OIDC_REDIRECT_URI))
