---
applications:
- name: npq-registration-sandbox
  processes:
  - type: web
    disk_quota: 2G
    memory: 2G
    health-check-http-endpoint: /healthcheck.json
    health-check-type: http
    health-check-invocation-timeout: 10
    instances: 2
  - type: worker
    disk_quota: 2G
    health-check-type: process
    instances: 1
    command: bundle exec rake jobs:work
  services:
    - npq-registration-sandbox-db
  env:
    DOCKER_IMAGE_ID: ((DOCKER_IMAGE_ID))
    ENV: $HOME/.profile
    SERVICE_ENV: sandbox
    SENTRY_CURRENT_ENV: sandbox
    SECRET_KEY_BASE: ((SECRET_KEY_BASE))
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    GOVUK_NOTIFY_API_KEY: ((GOVUK_NOTIFY_API_KEY))
    GOOGLE_TAG_MANAGER_ID: "GTM-N58Z5PG"
    GOOGLE_ANALYTICS_ID: "G-G3823VRN6N"
    ECF_APP_BASE_URL: "https://sb.manage-training-for-early-career-teachers.education.gov.uk/"
    ECF_APP_BEARER_TOKEN: ((ECF_APP_BEARER_TOKEN))
    SENTRY_DSN: ((SENTRY_DSN))
    TRA_OIDC_DOMAIN: ((TRA_OIDC_DOMAIN))
    TRA_OIDC_CLIENT_ID: ((TRA_OIDC_CLIENT_ID))
    TRA_OIDC_CLIENT_SECRET: ((TRA_OIDC_CLIENT_SECRET))
    TRA_OIDC_REDIRECT_URI: ((TRA_OIDC_REDIRECT_URI))
    GET_AN_IDENTITY_WEBHOOK_SECRET: ((GET_AN_IDENTITY_WEBHOOK_SECRET))
