---
applications:
- name: npq-registration-staging
  processes:
  - type: web
    disk_quota: 2G
    memory: 2G
    health-check-http-endpoint: /healthcheck.json
    health-check-type: http
    health-check-invocation-timeout: 10
    instances: 2
  - type: worker
    disk_quota: 2G
    health-check-type: process
    instances: 1
    command: bundle exec rake jobs:work
  services:
    - npq-registration-staging-db
  env:
    DOCKER_IMAGE_ID: ((DOCKER_IMAGE_ID))
    ECF_APP_BASE_URL: "https://st.manage-training-for-early-career-teachers.education.gov.uk/"
    ECF_APP_BEARER_TOKEN: ((ECF_APP_BEARER_TOKEN))
    ENV: $HOME/.profile
    GOOGLE_ANALYTICS_ID: "G-G3823VRN6N"
    GOOGLE_TAG_MANAGER_ID: "GTM-N58Z5PG"
    GOVUK_NOTIFY_API_KEY: ((GOVUK_NOTIFY_API_KEY))
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    SECRET_KEY_BASE: ((SECRET_KEY_BASE))
    SENTRY_CURRENT_ENV: staging
    SENTRY_DSN: ((SENTRY_DSN))
    SERVICE_ENV: staging

