name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install CloudFoundry CLI
        shell: bash
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get --allow-insecure-repositories update
          sudo apt-get --allow-unauthenticated install cf7-cli

      - name: Build and push Docker image
        id: docker_build
        uses: ./.github/actions/build-and-push-docker-image
        with:
          dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_DEV_PASSWORD }}
          tag: npq-registration-prod
          account: dfedigital/early-careers-framework-prod
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        env:
          CF_DOCKER_PASSWORD: ${{ secrets.DOCKER_DEV_PASSWORD }}
          PAAS_ORGANISATION: dfe
          # This is a shared PAAS space
          PAAS_SPACE: early-careers-framework-prod
          ENV_STUB: prod
          APP_NAME: npq-registration
          REMOTE_DOCKER_IMAGE_NAME: dfedigital/early-careers-framework-prod
          CF_USERNAME: ${{ secrets.GOVPAAS_PROD_USERNAME }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PROD_PASSWORD }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth
          cf target -o "${{ env.PAAS_ORGANISATION }}" -s "${{ env.PAAS_SPACE }}"
          cf push "${{ env.APP_NAME }}"-"${{ env.ENV_STUB }}" \
            --manifest ./config/manifests/"${{ env.ENV_STUB }}"-manifest.yml \
            --var DOCKER_IMAGE_ID="${{ steps.docker_build.outputs.docker_image_id }}" \
            --var SECRET_KEY_BASE="${{ secrets.RAILS_SECRET_KEY_BASE_PROD }}" \
            --var GOVUK_NOTIFY_API_KEY="${{ secrets.GOVUK_NOTIFY_API_KEY_PROD }}" \
            --var TRA_OIDC_DOMAIN="${{ secrets.TRA_OIDC_DOMAIN_PROD }}" \
            --var TRA_OIDC_CLIENT_ID="${{ secrets.TRA_OIDC_CLIENT_ID_PROD }}" \
            --var TRA_OIDC_CLIENT_SECRET="${{ secrets.TRA_OIDC_CLIENT_SECRET_PROD }}" \
            --var TRA_OIDC_REDIRECT_URI="${{ secrets.TRA_OIDC_REDIRECT_URI_PROD }}" \
            --var ECF_APP_BEARER_TOKEN="${{ secrets.ECF_APP_BEARER_TOKEN_PROD }}" \
            --var SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
            --var GET_AN_IDENTITY_WEBHOOK_SECRET="${{ secrets.GET_AN_IDENTITY_WEBHOOK_SECRET_PROD }}" \
            --docker-image "${{ env.REMOTE_DOCKER_IMAGE_NAME }}":"${{ env.APP_NAME }}"-"${{ env.ENV_STUB }}" \
            --docker-username "${{ secrets.DOCKER_USERNAME }}" \
            --strategy rolling

          cf run-task "${{ env.APP_NAME }}"-"${{ env.ENV_STUB }}" \
            --command "cd /app && /usr/local/bundle/bin/bundle exec rails feature_flags:initialize" \
            --process worker \
            --name initialize-feature-flags

      - name: Tag deployment
        run: |
          export TAG_FOR_RELEASE=prod-release-$(date +%Y-%m-%d-%H-%M)-$(git rev-parse --short HEAD)
          git tag --force $TAG_FOR_RELEASE
          git push --force origin refs/tags/$TAG_FOR_RELEASE
