name: "Deploy migration"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - npq-separation

  pull_request:
    branches:
      - npq-separation
    types:
      - labeled
      - synchronize
      - reopened
      - opened

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  rspec:
    name: RSpec
    uses: ./.github/workflows/rspec.yml

  all-checks-passed:
    name: All checks passed
    needs: [lint, rspec]
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'Linting and tests passed, this branch is ready to be merged into npq-separation'"

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    outputs:
      docker-image: ${{ steps.build-docker-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - uses: DFE-Digital/github-actions/build-docker-image@master
        id: build-docker-image
        with:
          docker-repository: ghcr.io/dfe-digital/npq-registration
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-migration:
    name: Deploy migration
    needs: [docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/npq-separation'
    environment:
      name: migration
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-environment-to-aks
        id: deploy
        with:
          environment: migration
          docker-image: ${{ needs.deploy-staging.outputs.docker-image }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          current-commit-sha: ${{ github.sha }}
          statuscake-api-token: ${{ secrets.STATUSCAKE_API_TOKEN }}
