name: "Lint"
on:
  workflow_call:
    inputs:
      ruby-version:
        description: Ruby version
        type: string
        required: false
        default: "3.3.4"
      node-version:
        description: Node version
        type: string
        required: false
        default: "20.15.1"

jobs:
  ruby_linting:
    name: "Lint ruby"
    env:
      GOVUK_NOTIFY_API_KEY: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Lint Ruby
        run: bundle exec rubocop

  scss_linting:
    name: "Lint SCSS"
    env:
      GOVUK_NOTIFY_API_KEY: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Lint SCSS
        run: |-
          bundle exec rake lint:scss

  # TODO: JS lint?
  # TODO: JS Erblint?
