name: "Set maintenance mode"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
        - review

      mode:
        required: true
        type: choice
        options:
        - enable
        - disable

permissions:
  id-token: write
  packages: write

jobs:
  set-maintenance-mode:
    name: Set maintenance mode
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}

    steps:
    - name: Notify Teams channel
      if: always()   # ensures this runs even if previous step fails
      run: |
        payload=$(jq -n \
          --arg status "${{ job.status }}" \
          --arg env "${{ inputs.environment }}" \
          --arg mode "${{ inputs.mode }}" \
          --arg repo "${{ github.repository }}" \
          --arg run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          '{text: ("Maintenance mode " + $mode + " on " + $env + " completed with status: " + $status + " (" + $repo + ") <" + $run_url + ">")}')

        curl -X POST -H 'Content-Type: application/json' \
          -d "$payload" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"