name: Restore Snapshot DB from production DB
on:
  schedule:
    - cron: "0 22 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub environment to backup and restore
        type: choice
        default: production
        options:
          - production
        required: true

jobs:
  backup-and-restore-production:
    runs-on: ubuntu-24.04
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backup and restore snapshot
        uses: ./.github/actions/backup-and-restore-snapshot-database
        with:
          environment: production
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
