name: "Run nightly migration"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub environment to run from
        type: choice
        default: production
        options:
          - production
        required: true
  # TEMP: disable while we do parity check analysis
  # schedule:
  #   - cron: "30 0 * * *" # Run at 12:30am, daily

jobs:
  run_migration:
    name: "Run nightly migration"
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubectl
        uses: DFE-Digital/github-actions/set-kubectl@master

      - name: Set AKS credentials (migration)
        shell: bash
        run: make ci migration get-cluster-credentials

      - name: Run migration
        shell: bash
        run: |
          kubectl -n cpd-production exec -ti --tty deployment/npq-registration-migration-web -- /bin/sh -c "cd /app && bundle exec rails runner \"Migration::Coordinator.prepare_for_migration; Migration::Coordinator.new.migrate!\""
